project_id = "uzynmjhrhdsqrnacryrw"

[functions.analyze-product]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false
